/**
 * School catalog types and data.
 *
 * The data lives in ./schools.json, generated by apps/map-scraper from
 * schools.txt (List of Government Schools - 2018). Run `uv run main.py` from
 * apps/map-scraper to refresh it. Sinhala labels and coordinates stay empty
 * until an authoritative source provides them; missing coordinates are filled
 * in by an admin through the schools hub and stored in the database.
 *
 * This module is the single place the raw JSON is given a type, so consumers
 * import SCHOOLS from here rather than reaching for the JSON directly.
 */
import schoolsJson from "./schools.json";

export type GenderType = "boys" | "girls" | "mixed";
export type SchoolType = "national" | "provincial";

export interface School {
  id: string;
  en: string;
  si: string;
  lat: number | null;
  lng: number | null;
  genderType: GenderType;
  schoolType: SchoolType;
  districtId: string;
  dsId: string;
}

export const SCHOOLS: School[] = schoolsJson as School[];
