/**
 * The school catalog, generated by apps/map-scraper and baked into ./schools at build
 * time - there is no database-backed override layer. A school with a missing or wrong
 * pin is fixed at the source (apps/map-scraper/map_coordinates.json for coordinates,
 * generator.py's STABLE_SCHOOLS for a display-name override) and the catalog is
 * regenerated with `uv run main.py` from apps/map-scraper, then redeployed - not
 * through the admin UI. Every deployment and every client sees the same list because
 * it ships with the bundle, with nothing to hydrate at boot.
 */
import { SCHOOLS, type School } from "./schools";

export function getSchools(): School[] {
  return SCHOOLS;
}

export function schoolsWithCoordinates(): Array<School & { lat: number; lng: number }> {
  return SCHOOLS.filter((school): school is School & { lat: number; lng: number } => school.lat !== null && school.lng !== null);
}

export function findSchoolById(id: string): School | undefined {
  return SCHOOLS.find((school) => school.id === id);
}
