/**
 * Runtime merge of manually administered school coordinates (DB overrides)
 * over the baked-in catalog in ./schools.
 *
 * The base catalog ships with the web bundle and is regenerated by the
 * map scraper.  Coordinates that admins add through the schools hub are
 * stored in the database and hydrated here at app boot (see main.tsx), so
 * every deployment and every client sees the same list without editing
 * checked-in JSON files.
 */
import { SCHOOLS, type School } from "./schools";
import { client } from "@/utils/orpc";

export type SchoolCoordinateOverride = {
  id: string;
  name: string;
  latitude: number;
  longitude: number;
  note: string | null;
  updatedBy: string;
  updatedAt: Date;
};

type AppliedOverride = {
  lat: number;
  lng: number;
  note?: string;
  updatedAt?: Date;
};

let overrides = new Map<string, AppliedOverride>();
let hydrated = false;

export function hasHydratedSchoolCoordinates(): boolean {
  return hydrated;
}

export function applySchoolCoordinateOverrides(rows: SchoolCoordinateOverride[]): void {
  const next = new Map<string, AppliedOverride>();
  for (const row of rows) {
    next.set(row.id, {
      lat: row.latitude,
      lng: row.longitude,
      note: row.note ?? undefined,
      updatedAt: row.updatedAt instanceof Date ? row.updatedAt : new Date(row.updatedAt),
    });
  }
  overrides = next;
  hydrated = true;
}

export function schoolCoordinateOverride(id: string): AppliedOverride | undefined {
  return overrides.get(id);
}

/** Re-fetch manual coordinates from the API (used at boot and after admin edits). */
export async function refreshSchoolCoordinateOverrides(): Promise<void> {
  try {
    const rows = await client.schools.overrides(undefined, {
      signal: AbortSignal.timeout(8_000),
    });
    applySchoolCoordinateOverrides(rows);
  } catch {
    // API unreachable (e.g. dev server offline) – keep the baked-in catalog.
  }
}

/** The catalog with manual overrides applied; overrides win over scrape coordinates. */
export function getSchools(): School[] {
  if (!hydrated || overrides.size === 0) return SCHOOLS;
  return SCHOOLS.map((school) => {
    const override = overrides.get(school.id);
    return override ? { ...school, lat: override.lat, lng: override.lng } : school;
  });
}

export function schoolsWithCoordinates(): Array<School & { lat: number; lng: number }> {
  return getSchools().filter((school): school is School & { lat: number; lng: number } => school.lat !== null && school.lng !== null);
}

export function findSchoolById(id: string): School | undefined {
  return getSchools().find((school) => school.id === id);
}
