import { useEffect, useState } from "react";
import { createFileRoute, Link, Outlet, useLocation } from "@tanstack/react-router";
import { AlertTriangle, ArrowLeft, BarChart3, CheckCircle2, FileWarning, KeyRound, LayoutDashboard, QrCode, ShieldCheck, Trash2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { consumeEventIterator } from "@orpc/client";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider } from "@aloysius-g1/ui/components/sidebar";
import { client, orpc } from "@/utils/orpc";
import { AccessKeyQrDialog } from "@/components/application/access-key-qr";

export const Route = createFileRoute("/_auth/admin")({ component: AdminPage });

function AdminPage() {
  const { session } = Route.useRouteContext();
  const location = useLocation();
  const overview = useQuery(orpc.admin.overview.queryOptions());
  const applications = useQuery(orpc.admin.applications.queryOptions({ input: { page: 1, pageSize: 50, query: "" } }));
  const settings = useQuery(orpc.admin.settings.get.queryOptions());
  const accessRequests = useQuery(orpc.admin.accessRequests.query.queryOptions());
  useEffect(() => { if (session.data?.user.role !== "admin") return; const controller = new AbortController(); const cancel = consumeEventIterator(client.application.liveCount(undefined, { signal: controller.signal }), { onEvent: () => { void overview.refetch(); void applications.refetch(); }, onError: () => undefined }); return () => { controller.abort(); cancel(); }; }, [session.data?.user.role]);
  if (session.data?.user.role !== "admin") return <main className="admin-shell admin-denied-shell"><section className="admin-card admin-denied-card"><div className="admin-denied-icon"><ShieldCheck size={28} /></div><h1>Admin access required</h1><p>Your account is signed in, but it does not have permission to view the operations dashboard.</p><Link className="primary-button" to="/dashboard"><ArrowLeft size={17} /> Back to dashboard</Link></section></main>;
  const metrics = [["Applications", overview.data?.total ?? "—", ShieldCheck], ["Drafts", overview.data?.drafts ?? "—", FileWarning], ["Submitted", overview.data?.submitted ?? "—", CheckCircle2], ["Incomplete", overview.data?.incomplete ?? "—", AlertTriangle], ["Invalid emails", overview.data?.invalidEmail ?? "—", AlertTriangle]] as const;
  return <SidebarProvider><Sidebar><SidebarHeader><div className="admin-brand"><div className="admin-brand-mark"><ShieldCheck size={19} /></div><div><strong>G1 Intake</strong><span>Admin console</span></div></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton href="/admin" active={location.pathname === "/admin"}><LayoutDashboard size={17} /> Overview</SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton href="/admin/applications" active={location.pathname === "/admin/applications"}><BarChart3 size={17} /> Applications</SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><Link className="admin-sidebar-back" to="/dashboard"><ArrowLeft size={16} /> Back to dashboard</Link></SidebarFooter></Sidebar>{location.pathname === "/admin" && <main className="admin-shell"><div className="admin-topbar"><div><p className="form-kicker">Operations</p><h1>G1 application control room</h1><p>Monitor saved applications, data quality, and submission progress.</p></div><span className="admin-live-status"><span /> Live via SSE</span></div>{overview.error && <div className="admin-card admin-error"><AlertTriangle size={18} /> Could not load admin metrics: {overview.error.message}</div>}<div className="admin-metrics">{metrics.map(([label, value, Icon]) => <div className="admin-metric" key={label}><Icon size={18} /><span>{label}</span><strong>{value}</strong></div>)}</div><FormWindowSettings settings={settings.data} /><AccessRequestQueue requests={accessRequests.data ?? []} onRefresh={() => void accessRequests.refetch()} /><section className="admin-card"><h2>Recent activity</h2><div className="admin-activity">{overview.data?.recent.map((item) => <div key={item.id}><span>{item.applicantName}</span><small>{item.status} · updated {new Date(item.updatedAt).toLocaleString()}</small></div>)}</div></section></main>}<Outlet /></SidebarProvider>;
}

function localDateTime(value: Date | string | undefined) { if (!value) return ""; const date = new Date(value); const pad = (part: number) => String(part).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }

function FormWindowSettings({ settings }: { settings?: { opensAt: Date; closesAt: Date } }) {
  const [opensAt, setOpensAt] = useState(""); const [closesAt, setClosesAt] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (settings) { setOpensAt(localDateTime(settings.opensAt)); setClosesAt(localDateTime(settings.closesAt)); } }, [settings]);
  const save = async () => { setSaving(true); setMessage(""); try { await client.admin.settings.update({ opensAt: new Date(opensAt), closesAt: new Date(closesAt) }); setMessage("Form window saved"); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save form window"); } finally { setSaving(false); } };
  return <section className="admin-card admin-window-card"><div><h2>Form availability</h2><p>Choose when applicants can submit the form. The window uses your local time.</p></div><div className="admin-window-fields"><label className="admin-field"><span>Opens</span><input type="datetime-local" value={opensAt} onChange={(event) => setOpensAt(event.target.value)} /></label><label className="admin-field"><span>Closes</span><input type="datetime-local" value={closesAt} onChange={(event) => setClosesAt(event.target.value)} /></label><button className="primary-button" type="button" disabled={saving || !opensAt || !closesAt} onClick={() => void save()}>{saving ? "Saving…" : "Save form window"}</button></div>{message && <p className="admin-inline-message" role="status">{message}</p>}</section>;
}

function AccessRequestQueue({ requests, onRefresh }: { requests: Array<{ id: string; applicantName: string; contactEmail: string; birthCertificateNumber: string; createdAt: Date }>; onRefresh: () => void }) {
  const [generatedKey, setGeneratedKey] = useState(""); const [qrKey, setQrKey] = useState(""); const [message, setMessage] = useState(""); const rotate = async (requestId: string) => { try { const result = await client.admin.accessRequests.rotateKey({ requestId }); setGeneratedKey(result.accessKey); setQrKey(result.accessKey); setMessage("New key generated. Share it securely with the verified applicant."); onRefresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not generate key"); } }; const dismiss = async (requestId: string) => { try { await client.admin.accessRequests.dismiss({ requestId }); onRefresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not dismiss request"); } };
  return <section className="admin-card admin-requests-card"><div className="admin-section-heading"><div><h2>Access-key requests</h2><p>Review applicants who lost access to an existing application.</p></div><span className="admin-status">{requests.length} open</span></div>{generatedKey && <div className="admin-generated-key"><strong>One-time display</strong><code>{generatedKey}</code><span>Copy this key now; it will not be shown again.</span><button className="secondary-button" type="button" onClick={() => setQrKey(generatedKey)}><QrCode size={16} /> Show QR code</button></div>}{message && <p className="admin-inline-message" role="status">{message}</p>}{requests.length === 0 ? <p className="admin-empty">No open access requests.</p> : <div className="admin-request-list">{requests.map((request) => <div className="admin-request-row" key={request.id}><div><strong>{request.applicantName}</strong><small>{request.contactEmail} · birth certificate ending {request.birthCertificateNumber.slice(-4)}</small><small>Requested {new Date(request.createdAt).toLocaleString()}</small></div><div className="admin-row-actions"><button className="secondary-button" type="button" onClick={() => void rotate(request.id)}><KeyRound size={15} /> Generate key</button><button className="icon-button danger" title="Dismiss request" type="button" onClick={() => void dismiss(request.id)}><Trash2 size={16} /></button></div></div>)}</div>}<AccessKeyQrDialog accessKey={qrKey} open={Boolean(qrKey)} onOpenChange={(open) => { if (!open) setQrKey(""); }} /></section>;
}
