import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronLeft, ChevronRight, ExternalLink, Globe, MapPin } from "lucide-react";
import { Badge } from "@aloysius-admissions/ui/components/badge";
import { Button } from "@aloysius-admissions/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@aloysius-admissions/ui/components/card";
import { Input } from "@aloysius-admissions/ui/components/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@aloysius-admissions/ui/components/select";
import { getSchools, schoolsWithCoordinates } from "@/lib/g1/school-coordinates";
import type { School } from "@/lib/g1/schools";
import { cn } from "@aloysius-admissions/ui/lib/utils";

export const Route = createFileRoute("/_auth/g1/admin/schools")({
  component: AdminSchoolsPage,
});

type Filter = "missing" | "located" | "all";

function prettySlug(value: string): string {
  return value.replace(/[-_]+/g, " ").trim().replace(/\b\w/g, (c) => c.toUpperCase()) || "Galle";
}

function searchLinks(school: School) {
  const place = `${school.en} ${prettySlug(school.dsId)} Galle, Sri Lanka`;
  const encoded = encodeURIComponent(place);
  return {
    maps: `https://www.google.com/maps/search/?api=1&query=${encoded}`,
    earth: `https://earth.google.com/web/search/${encoded}`,
    web: `https://www.google.com/search?q=${encodeURIComponent(`${school.en} ${prettySlug(school.dsId)} Galle school`)}`,
  };
}

function AdminSchoolsPage() {
  const [filter, setFilter] = useState<Filter>("missing");
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(25);

  const schools = getSchools();
  const located = schoolsWithCoordinates().length;

  const rows = useMemo(() => {
    const q = query.trim().toLowerCase();
    return schools
      .map((school) => ({ school, status: school.lat !== null && school.lng !== null ? ("located" as const) : ("missing" as const) }))
      .filter(({ school, status }) => {
        if (filter === "missing" && status !== "missing") return false;
        if (filter === "located" && status !== "located") return false;
        if (q && !`${school.en} ${school.id} ${school.dsId}`.toLowerCase().includes(q)) return false;
        return true;
      });
  }, [schools, filter, query]);

  useEffect(() => { setPage(0); }, [filter, query]);

  const totalPages = Math.ceil(rows.length / pageSize);
  const safePage = Math.min(page, Math.max(0, totalPages - 1));
  const paginatedRows = rows.slice(safePage * pageSize, (safePage + 1) * pageSize);

  const countBadge = (f: Filter) => {
    if (f === "missing") return schools.length - located;
    if (f === "located") return located;
    return schools.length;
  };

  const tabs: Array<{ id: Filter; label: string }> = [
    { id: "missing", label: "Missing coordinates" },
    { id: "located", label: "Located" },
    { id: "all", label: "All schools" },
  ];

  return (
    <main className="min-h-svh p-4 sm:p-8 lg:p-12.5 bg-[radial-gradient(circle_at_80%_0%,color-mix(in_oklch,var(--primary)_8%,transparent),transparent_32rem)]">
      <div className="flex flex-wrap items-end justify-between gap-4 sm:gap-8 mb-8">
        <div>
          <p className="text-primary font-bold tracking-widest uppercase text-xs">Workspace / Schools</p>
          <h1 className="font-heading text-[clamp(2rem,4vw,3.6rem)] mt-1 mb-3">Schools hub</h1>
          <p className="text-muted-foreground max-w-[70ch]">
            Every Galle government school needs coordinates for distance scoring and map views. The catalog (name, gender,
            district and coordinates) is generated by <code className="font-mono">apps/map-scraper</code> and ships with the
            app - there is no admin editor here anymore. To fix a missing or wrong entry: look it up via the search links
            below, add its coordinate to <code className="font-mono">apps/map-scraper/map_coordinates.json</code> (or a
            display-name override to <code className="font-mono">generator.py</code>'s <code className="font-mono">STABLE_SCHOOLS</code> if
            the government listing's name doesn't match the school's real name), run <code className="font-mono">uv run main.py</code> from
            that directory to regenerate the catalog, then redeploy.
          </p>
        </div>
        <Button variant="secondary" render={<Link to="/g1/admin/admin_map" search={true} />} nativeButton={false}><MapPin size={17} /> Open map view</Button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-6">
        <Card><CardContent className="pt-6"><p className="text-muted-foreground text-xs">Total schools</p><strong className="text-[1.8rem]">{schools.length}</strong></CardContent></Card>
        <Card><CardContent className="pt-6"><p className="text-muted-foreground text-xs">With coordinates</p><strong className="text-[1.8rem] text-emerald-600">{located}</strong></CardContent></Card>
        <Card><CardContent className="pt-6"><p className="text-muted-foreground text-xs">Missing</p><strong className="text-[1.8rem] text-amber-600">{countBadge("missing")}</strong></CardContent></Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">School coordinates</CardTitle>
          <CardDescription>Read-only view of the generated catalog. See above for how to correct an entry.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-3">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap items-center gap-2">
              <div className="flex flex-wrap gap-1.5">
                {tabs.map((tab) => (
                  <button
                    key={tab.id}
                    type="button"
                    onClick={() => setFilter(tab.id)}
                    className={cn(
                      "rounded-full px-3 py-1 text-xs font-semibold transition-colors",
                      filter === tab.id ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted",
                    )}
                  >
                    {tab.label} <span className="opacity-70">({countBadge(tab.id)})</span>
                  </button>
                ))}
              </div>
              {query && <span className="text-xs text-muted-foreground">{rows.length} result{rows.length !== 1 ? "s" : ""}</span>}
            </div>
            <div className="flex items-center gap-2">
              <Input
                placeholder="Search by name, id, or division…"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                className="h-8 w-full max-w-xs"
              />
              <Select value={String(pageSize)} onValueChange={(v) => { if (v) { setPageSize(Number(v)); setPage(0); } }}>
                <SelectTrigger className="h-8 w-[70px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="10">10</SelectItem>
                  <SelectItem value="25">25</SelectItem>
                  <SelectItem value="50">50</SelectItem>
                  <SelectItem value="100">100</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid gap-1">
            {rows.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No schools match this view.</p>}
            {paginatedRows.map(({ school, status }) => {
              const links = searchLinks(school);
              return (
                <div key={school.id} className="flex flex-wrap items-center gap-3 rounded-lg border px-3 py-2.5 text-sm hover:bg-muted/40">
                  <div className="min-w-0 flex-1">
                    <span className="font-medium">{school.en}</span>{" "}
                    {status === "located" && <Badge variant="outline" className="align-middle text-[0.65rem] text-emerald-600">Located</Badge>}
                    {status === "missing" && <Badge variant="destructive" className="align-middle text-[0.65rem]">Missing</Badge>}
                    <div className="text-xs text-muted-foreground">
                      <code className="font-mono">{school.id}</code> · {prettySlug(school.dsId)} · {school.genderType}/{school.schoolType}
                      {status === "located" && school.lat != null && <> · <code className="font-mono">{school.lat.toFixed(5)}, {school.lng?.toFixed(5)}</code></>}
                    </div>
                  </div>
                  <div className="flex flex-wrap items-center gap-1.5">
                    <Button type="button" variant="ghost" size="sm" render={<a href={links.maps} target="_blank" rel="noopener noreferrer" title="Search on Google Maps" />} nativeButton={false}><MapPin size={14} /> Maps</Button>
                    <Button type="button" variant="ghost" size="sm" render={<a href={links.earth} target="_blank" rel="noopener noreferrer" title="Search on Google Earth" />} nativeButton={false}><Globe size={14} /> Earth</Button>
                    <Button type="button" variant="ghost" size="sm" render={<a href={links.web} target="_blank" rel="noopener noreferrer" title="Search on Google" />} nativeButton={false}><ExternalLink size={14} /> Google</Button>
                  </div>
                </div>
              );
            })}
          </div>

          {totalPages > 1 && (
            <div className="flex items-center justify-between border-t pt-3">
              <span className="text-xs text-muted-foreground">
                Page {safePage + 1} of {totalPages} · {rows.length} school{rows.length !== 1 ? "s" : ""}
              </span>
              <div className="flex items-center gap-1">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  disabled={safePage === 0}
                  onClick={() => setPage((p) => Math.max(0, p - 1))}
                >
                  <ChevronLeft size={14} /> Prev
                </Button>
                {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                  const start = Math.max(0, Math.min(safePage - 2, totalPages - 5));
                  const pageNum = start + i;
                  if (pageNum >= totalPages) return null;
                  return (
                    <Button
                      key={pageNum}
                      type="button"
                      variant={pageNum === safePage ? "default" : "outline"}
                      size="sm"
                      className="min-w-9 px-1"
                      onClick={() => setPage(pageNum)}
                    >
                      {pageNum + 1}
                    </Button>
                  );
                })}
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  disabled={safePage >= totalPages - 1}
                  onClick={() => setPage((p) => Math.min(totalPages - 1, p + 1))}
                >
                  Next <ChevronRight size={14} />
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </main>
  );
}
